plugins {
    id 'java'
    id 'io.papermc.paperweight.userdev' version '1.7.7'
}

group = 'com.lyecocoworld'
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

processResources {
    filter {
        it.replace('${project.version}', project.version.toString())
    }
}

jar {
    archiveBaseName.set('AlexMobsServerSide')
    archiveClassifier.set('')

    from('alexsmobs') { into('alexsmobs') }
    from('craftengine') { into('craftengine') }
    from('assets') { into('assets') }
    from('data') { into('data') }
    from('worldgen_datapack') { into('worldgen_datapack/natures_spirit') }
    from('larion_worldgen_datapack') { into('worldgen_datapack/larion') }
}

build {
    dependsOn(jar)
}
